[package]
name = "crabdocs"
version = "0.3.0"
edition = "2024"
description = "A naive CLI tool for searching Rust crates on crates.io and browsing documentation from docs.rs."

[dependencies]
anyhow = "1.0"
clap = { version = "4.6", features = ["derive"] }
html2md = "0.2"
regex = "1.12"
reqwest = { version = "0.13", features = ["json", "query"] }
scraper = "0.27"
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.28", features = ["derive"] }
tokio = { version = "1.52", features = ["rt-multi-thread", "macros"] }

[lints.clippy]
pedantic = "warn"
