[package]
name = "crabdocs"
version = "0.1.0"
edition = "2024"
description = "A naive CLI tool for searching Rust crates on crates.io and browsing documentation from docs.rs."

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
html2md = "0.2.15"
reqwest = { version = "0.12.24", features = ["json"] }
scraper = "0.24.0"
serde = { version = "1.0.228", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
